### ISSUE TITLE
Unit 1.32.0 Release

### ISSUE THREAD

**Issue by tippexs** [nginx/unit-docs#104]
We are about launching Unit 1.32.0 and this requires some changes in our Docs as well. This Task-List is to keep track of the changes need and link the resulting PRs.

# Release 1.32.0

## Meta-Data
- Version String: 1.32.0
- Date: Feb 27, 2024

## News Items and Overview Page

- [x] Add a News Item to News / 2024 / Unit 1.32.0 Released. 
- [ ] Add an News Item to News - Unit 1.32.0 Released / Version 1.32.0 adds support for the WebAssembly Component Model / WASI 0.2 APIs, access Unit variables from NJS Scripting, conditional access logging and more! [Details](/news/2024/unit-1.32.0-released/)

## Unit Variable Updates
- [x]  Add the new Variable `request_id` to the [Variables page](https://unit.nginx.org/configuration/#variables). Text should be something like: contains a string that is formed using random data and can be used as a unique request identifier. 

## Conditional Access Logging
- [x] Add a new section “Conditional Access Log” to https://unit.nginx.org/configuration/#access-log. @Jcahilltorre this is the [commit message](https://github.com/nginx/unit/commit/4c91bebb50d06b28e369d68b23022caa072cf62d) providing some extra context as well.

## Docker
- [ ] Validate why Versions are not displayed anymore. See https://github.com/nginx/unit-docs/issues/105

## Startup-Shutdown
- [x] #107

## NJS Updates
-  [x] Bump NJS Version to 0.8.2 in [Scripting ](https://unit.nginx.org/scripting/#scripting). We have to be clear in the messag that 0.8.2 is the only version that will be supported by 1.32.0.
- [x] On Scripting we are referencing to `njs`. We should be more clear an spell it out as `NGINX JavaScript "njs"`. 
- [x] Change the overall messaging on https://unit.nginx.org/scripting/#scripting
  - [x]  Remove `Some request properties are exposed as njs objects or scalars`. All Variables from https://unit.nginx.org/configuration/#variables can be used using the `vars` Object inside NJS. Reference to the commit message https://github.com/nginx/unit/pull/1024#pullrequestreview-1857523658
  - [x] Add `if` to the list ob places where NJS can be used.
  - [ ] Add / Change the Examples on Scripting to reflect the use of the new variables using `vars.method` for example.

## WASM Updates
- [ ] Add a new News Entry for a WASM Blog Post
- [x] Change Enabling WebAssembly https://unit.nginx.org/howto/source/#source-wasm 
- [x] Change https://unit.nginx.org/installation/#prerequisites
  - [x] Add `WebAssembly Components WASI 0.2 wasi-http` to the list of App languages and platforms
  - [x] Add Optinal dependecies  `wasmtime for WebAssembly Support`
- [x] Change "Configuring Modules" https://unit.nginx.org/howto/source/#modules-webassembly 
- [x] Change "Configuration/Applications/WebAssembly Page" https://unit.nginx.org/configuration/#webassembly
  - [x] Introduce Tab-Layout
- [x] Change "How-To/App Samples/WebAssembly" Page https://unit.nginx.org/howto/samples/#sample-wasm
  - [x] Introduce Tab-Layout in the WebAssembly Section 
- [x] Change  "External Language Modules" https://unit.nginx.org/howto/modules/#external-language-modules.
  - [x]  Change `..unit-wasm module or during a source build` with `...language module or during a source build`. Links can stay in place.

**Comment by lcrilly** [comment]
> We should be more clear an spell it out as NGINX JavaScript Engine "njs".

I've never seen the word 'engine' used around njs before. "NGINX JavaScript (njs)" is enough.

**Comment by Jcahilltorre** [comment]
marked all the items that are in the draft already.

Missing some sections of the release news, the webassembly blog post, and the NJS examples that I can't figure out on my own.
