### ISSUE TITLE
Building from Source / WebAssembly sidebar links don't work

### ISSUE THREAD

**Issue by danielledeleo** [nginx/unit-docs#117]
![image](https://github.com/nginx/unit-docs/assets/667598/152b2714-f043-4557-8e2a-312d2950cf6b)

These anchors don't work as intended when the _> Enabling WebAssembly_ section is collapsed, which it is by default.

I don't think these need to be linked to from the sidebar, so we can just remove the `:toc:` line here:

https://github.com/nginx/unit-docs/blob/dcd2d7bb3e9b74583a49b3633eae8063ebdecaef/source/howto/source.rst?plain=1#L147-L154

**Comment by tippexs** [comment]
I agree! This should NOT be linked from the sidebar! Good catch!
