### ISSUE TITLE
Misleading application logging information

### ISSUE THREAD

**Issue by lcrilly** [nginx/unit-docs#147]
When explaining the `stderr` and `stdout` options, https://unit.nginx.org/configuration/#applications mentions that

> When running in --no-daemon mode, application output is always redirected to [Unit’s log file](https://unit.nginx.org/troubleshooting/#troubleshooting-log).

This is misleading because only stderr is redirected. stdout still defaults to /dev/null and cannot be redirected when using `--no-daemon` mode.

Fixing that is a separate issue (https://github.com/nginx/unit/issues/1178) but for now the docs should be clearer.

**Comment by ac000** [comment]
Hopefully this will clear things up...

When running with `--no-daemon`, `stdout` goes to the console (tty unit is running on)  and `stderr` goes to the unit log.  E.g

```sh
$ ps -ef | grep unit
andrew       804     775  0 13:23 pts/1    00:00:00 unit: main v1.33.0 [/opt/unit/sbin/unitd --no-daemon]
...
andrew       809     808  0 13:23 pts/1    00:00:00 unit: "test" application
$ ls -l /proc/809/fd/{1,2}
lrwx------ 1 andrew andrew 64 May 23 13:23 /proc/809/fd/1 -> /dev/pts/1
l-wx------ 1 andrew andrew 64 May 23 13:23 /proc/809/fd/2 -> /opt/unit/unit.log
```

The `stdout` and `stderr` config options have _no_ effect when running with `--no-daemon`.

When running as a daemon (I.e _without_ --no-daemon) then we have

```sh
$ ps -ef | grep unit
andrew       900       1  0 13:33 ?        00:00:00 unit: main v1.33.0 [/opt/unit/sbin/unitd]
...
andrew       909     908  0 13:33 ?        00:00:00 unit: "test" application
$ ls -l /proc/909/fd/{1,2}
lrwx------ 1 andrew andrew 64 May 23 13:33 /proc/909/fd/1 -> /dev/null
l-wx------ 1 andrew andrew 64 May 23 13:33 /proc/909/fd/2 -> /opt/unit/unit.log
```

When setting the `stdout` & `stderr` config settings, e.g

```json
            "stdout": "/tmp/unit-stdout.log",                                   
            "stderr": "/tmp/unit-stderr.log",
```

When running with`--no-daemon` we get

```sh
$ ps -ef | grep unit
andrew      1102     775  0 13:42 pts/1    00:00:00 unit: main v1.33.0 [/opt/unit/sbin/unitd --no-daemon]
...
andrew      1107    1106  0 13:42 pts/1    00:00:00 unit: "test" application
$ ls -l /proc/1107/fd/{1,2}
lrwx------ 1 andrew andrew 64 May 23 13:46 /proc/1107/fd/1 -> /dev/pts/1
l-wx------ 1 andrew andrew 64 May 23 13:46 /proc/1107/fd/2 -> /opt/unit/unit.log
```

No change...

Running as a **daemon**

```sh
$ ps -ef | grep unit
andrew      1220       1  0 13:47 ?        00:00:00 unit: main v1.33.0 [/opt/unit/sbin/unitd]
...
andrew      1229    1228  0 13:47 ?        00:00:00 unit: "test" application
$ ls -l /proc/1229/fd/{1,2}
l-wx------ 1 andrew andrew 64 May 23 13:48 /proc/1229/fd/1 -> /tmp/unit-stdout.log
l-wx------ 1 andrew andrew 64 May 23 13:48 /proc/1229/fd/2 -> /tmp/unit-stderr.log
```

The key to fixing https://github.com/nginx/unit/issues/1178 is to revert the change that started running unit with `--no-daemon`.

**Comment by MagnusOxlund** [comment]
What happens to `stdout` when Unit is run as a systemd service (with `--no-daemon`)?

**Comment by MagnusOxlund** [comment]
To answer my own question, it looks like `stdout` is sent to the systemd journal, which is different from Unit's own log file where `stderr` is sent.

How come `stderr` and `stdout` are separated?

Would it be possible to direct both to the same place?

Configuring the output `unit.service` file doesn't seem to affect this:

```
[Service]
StandardError=journal
StandardOutput=journal
```

**Comment by ac000** [comment]
With `--no-daemon`, `stdout` goes to the console, `stderr` goes to the unit log. When running under systemd, because there is then no direct console systemd will get `stdout`

> Would it be possible to direct both to the same place?

That _should_ work when _not_ using `--no-daemon` and using the `stdout` & `stderr` config options.

**Comment by ac000** [comment]
> Personally, I'm trying to direct both stdout and stderr to Unit's systemd journal to streamline log management. 

Have you tried this configuration...

In `/etc/systemd/system/unit.service`

```
[Service]
Type=forking
Environment="UNITD_OPTIONS=--log /var/log/unit/unit.log --pid /var/run/unit/unit.pid"
ExecStart=/usr/sbin/unitd $UNITD_OPTIONS
...
StandardOutput=journal
StandardError=journal
```

And in your unit application section

```json
"stdout": "/dev/stdout",
"stderr": "/dev/stderr"
```

> From your clarification, however, it sounds like Unit doesn't actually suppress stdout and that the behavior is not specific to WSGI apps?

IIRC `stdout` is suppressed, at least for some language modules... as I noted in the [commit message](https://github.com/nginx/unit/commit/45c45eaeb4443ff4af9cc49e716bbd9d65596b02)

```
    NOTE:
    
    You may or may not see stuff printed to stdout as stdout was
    traditionally used by CGI applications to communicate with the
    webserver.
```

**Comment by MagnusOxlund** [comment]
> Have you tried this configuration...

I have. Unfortunately `stderr` only shows up in `/var/log/unit/unit.log`.

I can get `stdout` to appear in the journal if I use `--no-daemon` but not without it.

**Comment by ac000** [comment]
_Without_ `--no-daemon` with a unit application config of

```json
"stdout": "/dev/stdout",
"stderr": "/dev/stderr"
```

Where does stdout/stderr go?

**Comment by Jcahilltorre** [comment]
@ac000 did the documentation changes address this ticket or is there is still more to do?

What is the acceptance criteria?

**Comment by ac000** [comment]
I think we can close this for now...
