### ISSUE TITLE
Break apart multi-command console blocks in docs

### ISSUE THREAD

**Issue by callahad** [nginx/unit-docs#172]
Many of our docs pages have `.. code-block:: console` blocks which contain multiple commands to be run in sequence.

A technical writer should decide whether we need to break each command into its own separate block.

The issue is that the "copy to clipboard" button places all of the commands from the block into the user's clipboard, separated by newlines. When pasted, all commands will execute unconditionally, even if an earlier command in the sequence fails. In the worst case, this could cause data loss.

**Comment by Jcahilltorre** [comment]
resolved in 147e7f0a6ffdaa3df7174864bf3fa19e0c7a1ff2
