### ISSUE TITLE
This also needs a followup on the docs repo, since this file is deployed to the website: https://github.com/nginx/unit-docs/blob/main/Makefile#L58

### ISSUE THREAD

**Issue by ac000** [nginx/unit-docs#175]
This also needs a followup on the docs repo, since this file is deployed to the website: https://github.com/nginx/unit-docs/blob/main/Makefile#L58

_Originally posted by @thresheek in https://github.com/nginx/unit/issues/1430#issuecomment-2353556039_

**Comment by Jcahilltorre** [comment]
What is the AC here @ac000 @callahad ? the ticket needs more context, ideally without having to jump to other tickets/PRs
