### ISSUE TITLE
Can the theme be reused?

### ISSUE THREAD

**Issue by abetkin** [nginx/unit-docs#31]
Hi @artemkonev,

I like the theme, can it be reused in other projects? What should be changed?

**Comment by artemkonev** [comment]
Hi, @abetkin,

I think we're in a bit of a legal limbo so far with the site sources, unfortunately.

I'll run this question with our copyright people and get back to you. Effectively, I foresee no issues with that, but the licensing for the theme and the extensions (if you want to use them too) may be different. Thanks for asking! I'll try to help you make that happen.

**Comment by artemkonev** [comment]
An update: it seems that a proper resolution might take a couple of weeks, so please bear with us.

**Comment by love01211** [comment]
I would also like to use this theme in continuous attention

**Comment by artemkonev** [comment]
@abetkin @love01211 After much deliberation, we agreed on CC BY 4.0: https://github.com/nginx/unit-docs/blob/master/LICENSE
