### ISSUE TITLE
install from Tarball

### ISSUE THREAD

**Issue by matt-horwood-mayden** [nginx/unit-docs#4]
I have run the install process on a raspberry pi to have a play before looking at work, but have hit some issues.

1. Configuring Sources - needs to have where to install unit to with --prefix
2. missing any sort of example config to work from
3. missing any init script for ether initd for systemd

Without #1 I cant get the make install to complete
Without #3 I dont know how to start unit and what options to fill in

Could the documents be updated to help?

**Comment by VBart** [comment]
Thank you. The documentation needs to be improved.
All configuration examples are in the [Configuration](http://unit.nginx.org/configuration/) section.

**Comment by VBart** [comment]
By the way, both `./configure` script and `unitd` binary have a `--help` option that provides some basic information about available parameters.

**Comment by artemkonev** [comment]
Hello,

1. http://unit.nginx.org/installation/#configuring-sources
    http://unit.nginx.org/installation/#building-and-installing-unit
2. http://unit.nginx.org/configuration/#full-example (a bit outdated, updates are coming)
3. On its way.

**Comment by matt-horwood-mayden** [comment]
Thanks @artemkonev 
I have used point 1 and 3 to get 3 of my web apps running with unit, the web app I want to make work is still proving difficult. But if you have any ideas on how to make Nextcloud work that would help.

**Comment by artemkonev** [comment]
Follow this thread for updates:
https://github.com/nginx/unit-docs/issues/8#issuecomment-505048472

> Hi,
> The [NextCloud] doc is almost ready and will be published soon, stay tuned.

**Comment by artemkonev** [comment]
http://unit.nginx.org/howto/nextcloud/
