### ISSUE TITLE
Does 30x really require a Location header?

### ISSUE THREAD

**Issue by alejandro-colomar** [nginx/unit-docs#43]
Regarding the following docs:

<https://github.com/nginx/unit-docs/blob/85744c8a1de8a8805950562cbecc4a40dde3af28/source/configuration.rst#instant-responses-redirects>
```rst
$ grep -rn -B1 'required if the'
source/configuration.rst-1976-   * - :samp:`location`
source/configuration.rst:1977:     - URI, required if the :samp:`return` value implies redirection.
```

The current behavior of Unit is that the `"location"` URI is optional.  The following is allowed:

```json
"action": {
    "return": 301
}
```

Also, the current RFC doesn't seem to explicitly require (or I couldn't find it) that a Location header is used for 30x redirects:
<https://www.rfc-editor.org/rfc/rfc7231#section-7.1.2>

Should we reword that?

See also: <https://github.com/nginx/unit/issues/674>

**Comment by artemkonev** [comment]
A summary of the 30x codes shows that 'required if redirection is implied' is more suitable than not, so I'd rather leave this as is:

https://www.rfc-editor.org/rfc/rfc7231#section-6.4
```
300 Multiple Choices

   If the server has a preferred choice, the server SHOULD generate a
   Location header field containing a preferred choice's URI reference.

301 Moved Permanently

   The server SHOULD generate a Location header field in the response
   containing a preferred URI reference for the new permanent URI.

302 Found

   The server SHOULD generate a Location header field in the response
   containing a URI reference for the different URI.

303 See Other

   The 303 (See Other) status code indicates that the server is
   redirecting the user agent to a different resource, as indicated by a
   URI in the Location header field, which is intended to provide an
   indirect response to the original request.

 307 Temporary Redirect

   The server SHOULD generate a Location header field in the response
   containing a URI reference for the different URI. 
```
