### ISSUE TITLE
aiohttp Example

### ISSUE THREAD

**Issue by 4n1qz5skwv** [nginx/unit-docs#46]
It would be nice to have a working example of https://docs.aiohttp.org/en/stable/web.html

I already tried with basic asgi protocol approach, but it is not working.
https://github.com/aio-libs/aiohttp/issues/7017

**Comment by artemkonev** [comment]
@4n1qz5skwv Hi, I'll see what can be done about that.

**Comment by artemkonev** [comment]
@4n1qz5skwv It appears that `aiohttp` acts a web server in its own right, which doesn't make it a good choice to run on NGINX Unit. Unit (Python-wise) is aimed at WSGI/ASGI apps and frameworks.
