### ISSUE TITLE
Invalid control socket path with Homebrew installation

### ISSUE THREAD

**Issue by kate-goldenring** [nginx/unit-docs#47]
I followed these [instructions for installing unit via Homebrew](https://unit.nginx.org/installation/#homebrew). However, the socket is never created at the expected control path, resulting in an error connecting to the server:
```sh
kagold@Kates-MacBook-Pro unit % curl -X PUT --data-binary @config.json --unix-socket /usr/local/var/run/unit/control.sock http://localhost/config/applications
curl: (7) Couldn't connect to server
```

Instead, the socket was created at `/opt/homebrew/var/run/unit/control.sock`. Querying unit with that control socket succeeds. It appears that the docs may need to be updated.

My device info: macOS 12.6, Apple M1 Pro (arm)

**Comment by tippexs** [comment]
Hi @kate-goldenring thanks for reaching out. We will have a look on thins and I will keep you posted here.

**Comment by artemkonev** [comment]
@kate-goldenring Hi, couldn't easily reproduce this bug here, can you please share the output of these two commands:
```console
$ brew config
$ unitd --version
```

**Comment by artemkonev** [comment]
@kate-goldenring figured that out, Homebrew uses different prefixes on different architectures. Please see the updated docs: https://unit.nginx.org/installation/#homebrew

**Comment by lcrilly** [comment]
@kate-goldenring we're looking into providing a command line tool that would hide the low-level socket details. I'd be pleased to get any feedback on this simple curl wrapper, if it makes your life easier?

https://github.com/lcrilly/unitc
