### ISSUE TITLE
Small bug in setup-unit shell script on line 12 causing failure

### ISSUE THREAD

**Issue by figuerom16** [nginx/unit-docs#49]
Located under: https://unit.nginx.org/installation/#repo-install
This script: https://unit.nginx.org/_downloads/setup-unit

Script has small bug on line 12 causing the script to throw a syntax error:
./setup-unit: line 731: syntax error near unexpected token '}'
./setup-unit: line 731: '}'

Line 12 is: `>&2 echo 'Your version of bash(1) isn't supported by this script.';`
An extra open single quote is causing the bulk of the script to become a string

Line 12 should be: `>&2 echo "Your version of bash(1) isn't supported by this script.";`
Swapping out single quotes for double and the script executes perfectly on Debian 11.5

**Comment by tippexs** [comment]
Thanks! We already aware of it and we will push a new version the next days. Christmas as coming in the way 🎄

Thanks for reporting this. I will let you know once we have pushed the fix so you can test it again.

Thanks for sharing

**Comment by artemkonev** [comment]
@figuerom16 could you please try again?

**Comment by figuerom16** [comment]
The new script target at https://raw.githubusercontent.com/nginx/unit/master/tools/setup-unit works perfectly now on Debian 11.5.
Thank you!
