### ISSUE TITLE
Extra steps requred to run Unit as root on macOS

### ISSUE THREAD

**Issue by ac000** [nginx/unit-docs#61]
To summarise https://github.com/nginx/unit/issues/970, in order to run Unit as root under macOS you need to do the following

```shell
$ export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
$ sudo --preserve-env=OBJC_DISABLE_INITIALIZE_FORK_SAFETY /path/to/unitd args ...
```
If there's a suitable place to mention this...

**Comment by tippexs** [comment]
I would place this information in the Homebrew section for now. https://unit.nginx.org/installation/#homebrew
