### ISSUE TITLE
Rewrite curl requests to unitc unit

### ISSUE THREAD

**Issue by Pavlusha311245** [nginx/unit-docs#73]
I suggest to update the documentation and replace all curl queries with unitc tool. Or add tabs and provide 2 curl and unitc options
What do you think @lcrilly?

**Comment by lcrilly** [comment]
You read my mind! I am in favour of the tabs approach (with some state to remember which tab the reader prefers). Later we might have several API tools documented.

**Comment by Pavlusha311245** [comment]
I'd try to do it in my spare time, but I'm not sure it would be quick)

**Comment by Jcahilltorre** [comment]
@callahad does this need to be re-assigned? I think this change does not require tech writer input at all.

**Comment by callahad** [comment]
Agreed it's out of scope for tech writers (unless we change surrounding prose when making these edits.)

I'm going to close this as not planned; we either want `unitctl` or raw `curl` in the docs; `unitc` occupies a weird in-between space.
