### ISSUE TITLE
Integrate unit-docs with Netlify

### ISSUE THREAD

**Issue by callahad** [nginx/unit-docs#75]
Right now the Unit docs are manually built and deployed; we have an account with Netlify we can use to automate this, and get nice things like PR previews.

- [x] Hook up Netlify to this repo
- [x] Ensure [deploy previews](https://docs.netlify.com/site-deploys/deploy-previews/) are enabled and working
- [x] Create DNS record for sources.nginx.org
- [x] Make Unit releases available on sources.nginx.org/unit
- [x] Update #90 to reflect new canonical source tarball location
- [x] Flip DNS for unit.nginx.org to point to our Netlify-hosted docs

A couple extra tasks:

- [x] Decide what to do with sitemap.xml (Google no longer accepts sitemap pings)
- [x] Edit Makefile to copy over security.txt before deployment

cc: @jcahilltorre

**Comment by danielledeleo** [comment]
A couple extra tasks:

- [ ] Decide what to do with sitemap.xml (Google no longer accepts sitemap pings)
- [ ] Edit Makefile to copy over security.txt before deployment

**Comment by callahad** [comment]
> Decide what to do with sitemap.xml (Google no longer accepts sitemap pings)

I'd suggest we continue generating and publishing a valid sitemap.xml. Sitemaps are [still supported](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#addsitemap), it's just that the unauthenticated pings have gone away.

> Ensure [deploy previews](https://docs.netlify.com/site-deploys/deploy-previews/) are enabled and working

For future reference, we had to flip a setting in the Netlify console to allow deploy previews from untrusted users:

<img width="702" alt="Screenshot 2024-01-10 at 15 45 05" src="https://github.com/nginx/unit-docs/assets/24193/4da094fa-d5bb-48d6-9ec2-fdad235cac87">

**Comment by danielledeleo** [comment]
I think we're pretty much ready to go with the DNS change over.
