### ISSUE TITLE
Signature in security.txt is expired

### ISSUE THREAD

**Issue by danielledeleo** [nginx/unit-docs#77]
https://github.com/nginx/unit-docs/blob/1cb3f71fb52f77de43f0b032964e9f24b6554ac7/security.txt#L12-L14 The same file also exists in [nginx/unit/security.txt](https://github.com/nginx/unit/blob/master/security.txt)

It appears the signature expired at the beginning of the year. From what I can tell, this practice isn't done elsewhere within NGINX (.org or .com)—I'm not sure about other F5 projects.

I see a few different ways forward:

- a) Create an automated process to resign the security notice on a regular interval
- b) Make it expire more quickly so that someone manually re-signs the notice so that it isn't forgotten (perhaps with automated reminder emails)
- c) Remove the cryptographic signature

See https://securitytxt.org/ for what this file is for and the excellent rationale behind it.

**Comment by thresheek** [comment]
(As the person who signed the file previously, I can do it again)

**Comment by danielledeleo** [comment]
> (As the person who signed the file previously, I can do it again)

Please do! I think that is acceptable.

**Comment by danielledeleo** [comment]
https://github.com/nginx/unit/pull/1057 has been merged.
