### ISSUE TITLE
Unit-PHP + Nginx + NextCloud

### ISSUE THREAD

**Issue by Peter2121** [nginx/unit-docs#8]
It would be nice to have a working example of configuration for NextCloud installation using Unit-PHP and Nginx.

**Comment by artemkonev** [comment]
Hi,

A NextCloud howto is already in our plans for further work.

**Comment by Peter2121** [comment]
I'm in trouble trying to get it working, I get cyclic 302 redirect. Please, put any information on the subject into the docs.

**Comment by artemkonev** [comment]
Hi,
The doc is almost ready and will be published soon, stay tuned.

**Comment by artemkonev** [comment]
http://unit.nginx.org/howto/nextcloud/

**Comment by kennethlau** [comment]
> http://unit.nginx.org/howto/nextcloud/

 "applications": {
        "nextcloud": {
            "type": "php",
            "targets": {
                "direct": {
                    "root": "/path/to/app/"
                },

                "index": {
                    "root": "/path/to/app/",
                    "script": **"script":** "index.php"
                },

                "ocm": {
                    "root": "/path/to/app/ocm-provider/",
                    "script": **"script":** "index.php"
                },

                "ocs": {
                    "root": "/path/to/app/ocs-provider/",
                    "script": **"script":** "index.php"
                },

                "updater": {
                    "root": "/path/to/app/**nextcloud**/updater/",
                    "script": **"script":** "index.php"
                }
            }
        }
    }
